# Generated by Django 5.2.8 on 2025-11-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_id', models.PositiveIntegerField()),
                ('doctor_id', models.PositiveIntegerField()),
                ('plan_id', models.PositiveIntegerField()),
                ('invoice_number', models.CharField(max_length=512)),
                ('amount', models.IntegerField()),
                ('discount_amount', models.IntegerField()),
                ('final_amount', models.IntegerField()),
                ('invoice_file', models.BinaryField(blank=True, null=True)),
                ('invoice_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_generated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'INVOICES',
                'managed': False,
            },
        ),
    ]
