# Generated by Django 5.2.7 on 2025-11-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(db_column='DOCTOR_ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='DOCTOR_FIRST_NAME', max_length=64)),
                ('last_name', models.CharField(db_column='DOCTOR_LAST_NAME', max_length=64)),
                ('gender', models.CharField(db_column='GENDER', max_length=16)),
                ('country_code', models.IntegerField(db_column='COUNTRY_CODE')),
                ('mobile', models.CharField(db_column='MOBILE', max_length=16)),
                ('email', models.EmailField(db_column='EMAIL', max_length=128)),
                ('specialization', models.CharField(blank=True, db_column='SPECIALIZATION', max_length=255, null=True)),
                ('qualification', models.CharField(blank=True, db_column='QUALIFICATION', max_length=255, null=True)),
                ('mobile_number_verified', models.BooleanField(db_column='MOBILE_NUMBER_VERIFIED', default=False)),
                ('email_verified', models.BooleanField(db_column='EMAIL_VERIFIED', default=False)),
                ('street', models.TextField(blank=True, db_column='STREET', null=True)),
                ('area', models.CharField(blank=True, db_column='AREA', max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_column='CITY', max_length=255, null=True)),
                ('state', models.CharField(blank=True, db_column='STATE', max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, db_column='ZIPCODE', max_length=255, null=True)),
                ('country', models.CharField(blank=True, db_column='COUNTRY', max_length=264, null=True)),
                ('practice_name', models.CharField(blank=True, db_column='PRACTICE_NAME', max_length=1024, null=True)),
                ('hospital_name', models.CharField(blank=True, db_column='HOSPITAL_NAME', max_length=255, null=True)),
                ('hospital_address', models.CharField(blank=True, db_column='HOSPITAL_ADDRESS', max_length=512, null=True)),
                ('clinic_zipcode', models.CharField(blank=True, db_column='CLINIC_ZIPCODE', max_length=50, null=True)),
                ('birthday', models.DateField(blank=True, db_column='DOCTOR_BIRTHDAY', null=True)),
                ('marriage_anniversary', models.DateField(blank=True, db_column='DOCTOR_MARRIAGE_ANNIVERSARY', null=True)),
                ('list_of_services_offered', models.TextField(blank=True, db_column='LIST_OF_SERVICES_OFFERED', null=True)),
                ('gbp_available', models.BooleanField(db_column='GBP_AVAILABLE', default=False)),
                ('working_hours', models.CharField(blank=True, db_column='WORKING_HOURS', max_length=128, null=True)),
                ('designation', models.CharField(blank=True, db_column='DESIGNATION', max_length=128, null=True)),
                ('professional_experience_years', models.IntegerField(blank=True, db_column='PROFESSIONAL_EXPERIENCE_YEARS', null=True)),
                ('introduction', models.TextField(blank=True, db_column='INTRODUCTION', null=True)),
                ('publications_achievements', models.TextField(blank=True, db_column='PUBLICATIONS_ACHIEVEMENTS', null=True)),
                ('memberships', models.TextField(blank=True, db_column='MEMBERSHIPS', null=True)),
                ('doctor_photo', models.CharField(blank=True, db_column='DOCTOR_PHOTO', max_length=255, null=True)),
                ('departments', models.TextField(blank=True, db_column='DEPARTMENTS', null=True)),
                ('preferred_world_days', models.TextField(blank=True, db_column='PREFERRED_WORLD_DAYS', null=True)),
                ('language_preference', models.TextField(blank=True, db_column='LANGUAGE_PREFERENCE', null=True)),
                ('language_triggers', models.TextField(blank=True, db_column='LANGUAGE_TRIGGERS', null=True)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('billing_entity_name', models.CharField(blank=True, db_column='BILLING_ENTITY_NAME', max_length=255, null=True)),
                ('alternate_contact_name', models.CharField(blank=True, db_column='ALTERNATE_CONTACT_NAME', max_length=64, null=True)),
                ('alternate_contact_number', models.CharField(blank=True, db_column='ALTERNATE_CONTACT_NUMBER', max_length=16, null=True)),
                ('mail_verification_token', models.CharField(blank=True, db_column='MAIL_VERIFIFCATION_TOKEN', max_length=512, null=True)),
                ('gst_no', models.CharField(blank=True, db_column='GST_NO', max_length=32, null=True)),
                ('otp', models.CharField(blank=True, db_column='OTP', max_length=10, null=True)),
                ('otp_generated_time', models.DateTimeField(blank=True, db_column='OTP_GENERATED_TIME', null=True)),
                ('password', models.TextField(blank=True, db_column='PASSWORD', null=True)),
                ('username', models.TextField(blank=True, db_column='USERNAME', null=True)),
            ],
            options={
                'db_table': 'DOCTOR',
                'ordering': ['-created_at'],
            },
        ),
    ]
