# Generated by Django 5.2.8 on 2025-11-17 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('PLAN_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PLAN_NAME', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'PLANS',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('COUPON_ID', models.AutoField(primary_key=True, serialize=False)),
                ('COUPON_NAME', models.CharField(max_length=64)),
                ('PERCENTAGE', models.IntegerField()),
                ('ALL_PLANS', models.BooleanField(default=False)),
                ('IS_ACTIVE', models.BooleanField(default=False)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('PLAN_ID', models.ForeignKey(db_column='PLAN_ID', on_delete=django.db.models.deletion.CASCADE, to='coupons.plan')),
            ],
            options={
                'db_table': 'COUPONS',
            },
        ),
    ]
