# Generated by Django 5.2.8 on 2025-11-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('PLAN_ID', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'PLANS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanFeatures',
            fields=[
                ('FEATURE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('FEATURE_NAME', models.CharField(max_length=64)),
                ('FEATURE_COUNT', models.IntegerField()),
                ('IS_ACTIVE', models.BooleanField(default=False)),
                ('CREATED_AT', models.DateTimeField()),
                ('UPDATED_AT', models.DateTimeField()),
            ],
            options={
                'db_table': 'PLAN_FEATURES',
                'managed': False,
            },
        ),
    ]
